### ISSUE TITLE
Look into deployment with Docker

### ISSUE THREAD

**Issue by edipetres** [Praqma/questionnaire-engine#125]

**Comment by buep** [comment]
You want to achieve the vision in this drawing, including the updates you will do to the drawing in #124 


https://github.com/Praqma/questionnaire-engine/blob/master/docs/deployment-description.png


I recommend you start making it work locally, and skip the deployment pipelines so if you can create a docker file, build an image locally for the engine and re-use that for building the content image on.

So create a dockerfile for the engine, and build it.

Use it to base your dockerfile for the content image on, and figure out how to build it.

Then you should be able to run the final image on your local laptop browsing to the running container.

Your content deployment is a compose-file, because you need the mongodb instance running as part of that.

You will need to create issues  new workable issues, I'm making this a briefing now so please create new smaller workable issues, and mention this issue on them so the link in.

**Comment by edipetres** [comment]
closed in #126
