### ISSUE TITLE
Review questionnaire pipeline

### ISSUE THREAD

**Issue by edipetres** [Praqma/questionnaire-engine#146]
With regard to my meeting with Bue

- questionnaire-engine
- questionnaire-models
- #143 settle on design decisions

**Comment by buep** [comment]
Feedback

## engine pipeline

* The release step I prefer always is manual, I don't want a new questionnaire-engine release just because I edit a typo in the readme. So make the release job that pushes manually executed so someone with access can click run to create the release.
* version is hard-coded in the build step, this means you will edit the build step when you want a version bump. Confusing for other why the build definition file is changed, when build definition is not changed. The version number needs to come from a file, e.g. version.sh with major minor patch number so when one needs to change version that file is the one to edit. Appeding the CI build number is good as you already do
* the tag you use on docker hub for release number, should also be present at the same git sha in github, so remember to tag the github repo also
* the docker hub repo misses readme description, it should show the same content at the github readme and be automatically updated or posted there - all the information should be alligned
* I can't find the credentials in our password management system, when I search for AWS there is nothing related to questionnaire.... so either point to specific token or a better text to search for, or explain more precise in the readme which account is used. e.g. for example you only write "AWS_ACCESS_KEY_ID | Acces key for the AWS account the pipeline deploys to" but that doesn't tell me what to look for in our internal list
* I'm missing test steps, that shows the container can be started and serve a questionnaire with the demo content - else we risk publishing a container engine that doesn't work

## content pipeline

* same observations as above with version number
*  same things with docker hub readme and description, should be automated and contain proper content
* also need to explain why there is an AWS version number also
* missing a test step that make sure the container can run and serve the questionnaire locally before deployed to AWS
* all steps here in the content pipeline is fine to be fully automated and deployment to happen automatically

**Comment by buep** [comment]
On a general note... think we should create a questionnaire-meta repo with much of the generic content that explains the hole overview about engine and model... and then point to the concrete ones.

Let's discuss some improve docs - there are so much fine documentation you create, we just need to structure it a bit further for others to understand it.

**Comment by buep** [comment]
one last thing.... do we not have a Praqma circle ci organisation? this looks strange (see picture)

![image](https://user-images.githubusercontent.com/1579826/35920194-7a9201d0-0c17-11e8-96f1-280d62d0f5fa.png)

**Comment by edipetres** [comment]
@buep not sure what's wrong on the picture, I use the pipeline with the Praqma organization account on CircleCI

**Comment by buep** [comment]
Shouldn't the circle ci organisation be called Praqma? Or maybe it is because I'm not member?

**Comment by edipetres** [comment]
It is called Praqma for me - so maybe you need to be a member.. but that Bitbucket name is weird.

Closing this as we created new issues for all the points here.
