### ISSUE TITLE
Test that the newly built docker image serves the website correctly as a pipeline step

### ISSUE THREAD

**Issue by edipetres** [Praqma/questionnaire-engine#151]
- When building a new image test that the container runs the website without crashing - sending a proper response. Maybe do some smoke testing.
- Look at testing frameworks like Cucumber..

Test at least that the image runs properly. Could also test that the deployment to AWS worked and the website responds.

Use [phantom.js](http://phantomjs.org/)

**Comment by edipetres** [comment]
When running a docker container as a pipeline step, circleci will use a remote host (via TCP connection) to run the container in. Thus the website in the container will not be accessible on the localhost of the ci server, but instead on a remote Docker host, which cannot be accessed. 

This means that we cannot do a `curl localhost:3000` to see the running application, therefore smoke testing on the CI server is not possible with the current setup.

A solution could be to use a different executor type on CircleCI to running Docker images inside a virtual machine instead of a remote Docker host. Learn more about executor types [here](https://circleci.com/docs/2.0/executor-types/). I'm not confident that this switch could be quick enough to be worth it. 

I have also contacted Leonard, but he didn't have anything on top of his mind either at the moment. I will wait for your feedback on this, @buep

**Comment by buep** [comment]
So maybe we go with our second option we discussed? That was instead of testing on a local docker instance, we would make a test deployment to AWS and test on that?

The benefit of doing so is that we also get to test deployment steps each time we run smoke- or functional tests.

But it requires some extra work:

* you deployment automation must support a parameter saying if it is `prod` or ` test` environment, and then depending on that deployment file will be configured to deploy to for example for test to `myquestionnarie1.prod.questionnaires.praqma.com` (alias `myquestionnarie1.questinnaires.praqma.com` and for test to `myquestionnarie1.test.questinnaires.praqma.com`.
* you will have to have two AWS setups runnings costing the double amount of money, but preferable the test environment is shutdown when deployment to prod happens or after some timeout.

Try to figure out what you need for the above setup, and create a new set of issues for it - I think we should go with a `test` + `prod` setup for running tests instead.

**Comment by edipetres** [comment]
fixed in #164
